[package]
name = "declimiter"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
log = "0.4.29"
simple_logger = "5.1.0"
clap = { version = "4.5.49", features = ["default", "color", "help", "suggestions", "error-context"] }
clap_derive = "4.5.49"
declimiter-lib = { path = "src/declimiter-lib"}
thiserror = "2.0.18"
futures = { version = "0.3.31", features = []}
ratatui = "0.30.0"
eframe = "0.30"
egui_extras = "0.30"
windows = { version = "0.62", features = ["Win32_System_Console"] }
image = "0.25.10"

[build-dependencies]
winresource = "0.1.31"
